function formatDate(date) {
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const yyyy = date.getFullYear();
  return `${mm}/${dd}/${yyyy}`;
}

function yearsAgo(years) {
  const d = new Date();
  d.setFullYear(d.getFullYear() - years);
  return formatDate(d);
}

function monthsAndDaysFromNow(months, days) {
  const d = new Date();
  d.setMonth(d.getMonth() + months);
  d.setDate(d.getDate() + days);
  return formatDate(d);
}

class VehicleInsuranceTestData {
  constructor() {
    this.scenarios = {
      straightThrough: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 331.0,
          gold: 977.0,
          platinum: 1917.0,
          ultimate: 3652.0,
        },
      },
      enginePerformance1000to2000: {
        enginePerformance: 1500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 337.0,
          gold: 993.0,
          platinum: 1949.0,
          ultimate: 3712.0,
        },
      },
      manufacturedMoreThan5Years: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(10),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 334.0,
          gold: 983.0,
          platinum: 1931.0,
          ultimate: 3678.0,
        },
      },
      listPriceBetween50kAnd100k: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 75000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 466.0,
          gold: 1374.0,
          platinum: 2697.0,
          ultimate: 5137.0,
        },
      },
      ageBetween18and25: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 21,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 331.0,
          gold: 977.0,
          platinum: 1917.0,
          ultimate: 3652.0,
        },
      },
      ageBetween56and70: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 62,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 331.0,
          gold: 977.0,
          platinum: 1917.0,
          ultimate: 3652.0,
        },
      },
      female: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Female",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 331.0,
          gold: 977.0,
          platinum: 1917.0,
          ultimate: 3652.0,
        },
      },
      startDateMonthAfterNextMonth: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(2, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 331.0,
          gold: 977.0,
          platinum: 1917.0,
          ultimate: 3652.0,
        },
      },
      insuranceSumBetween15MAnd35M: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 25000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 338.0,
          gold: 995.0,
          platinum: 1953.0,
          ultimate: 3721.0,
        },
      },
      meritRatingSuperBonus: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Super Bonus",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 322.0,
          gold: 948.0,
          platinum: 1861.0,
          ultimate: 3546.0,
        },
      },
      meritRatingMalusBetween10and17: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Malus 13",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 370.0,
          gold: 1090.0,
          platinum: 2141.0,
          ultimate: 4078.0,
        },
      },
      damageInsuranceNoCoverage: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "No Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 282.0,
          gold: 832.0,
          platinum: 1634.0,
          ultimate: 3112.0,
        },
      },
      damageInsuranceFullCoverage: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Full Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 348.0,
          gold: 1027.0,
          platinum: 2017.0,
          ultimate: 3841.0,
        },
      },
      euroProtection: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: true,
        legalDefenseInsurance: true,
        courtesyCarOption: "No",
        prices: {
          silver: 333.0,
          gold: 981.0,
          platinum: 1927.0,
          ultimate: 3670.0,
        },
      },
      optionalProducts3: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: true,
        legalDefenseInsurance: false,
        courtesyCarOption: "No",
        prices: {
          silver: 283.0,
          gold: 833.0,
          platinum: 1636.0,
          ultimate: 3117.0,
        },
      },
      courtesyCar: {
        enginePerformance: 500,
        dateOfManufacture: yearsAgo(3),
        numberOfSeats: 5,
        fuelType: "Petrol",
        listPrice: 20000,
        annualMileage: 50000,
        age: 26,
        gender: "Male",
        country: "United States",
        occupation: "Employee",
        preferredStartDate: monthsAndDaysFromNow(1, 1),
        insuranceSum: 7000000,
        meritRating: "Bonus 5",
        damageInsurance: "Partial Coverage",
        euroProtection: false,
        legalDefenseInsurance: true,
        courtesyCarOption: "Yes",
        prices: {
          silver: 342.0,
          gold: 1009.0,
          platinum: 1980.0,
          ultimate: 3772.0,
        },
      },
    };
  }

  getScenario(scenarioName) {
    return this.scenarios[scenarioName];
  }

  getAllScenarios() {
    return this.scenarios;
  }
}

export default VehicleInsuranceTestData;
