name: PR Quality Checks

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    name: Quality Gates and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: Taucher/PT/Code/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: Taucher/PT/Code

      - name: Run ESLint (Quality Gate)
        run: npm run lint
        working-directory: Taucher/PT/Code

      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: Taucher/PT/Code

      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: Taucher/PT/Code

      - name: Run All Tests with Coverage
        run: npm test
        working-directory: Taucher/PT/Code

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
