name: WebdriverIO Tests

on:
  push:
    branches: [main]
    paths:
      - "Horvath/PT/Code/**"
  pull_request:
    branches: [main]
    paths:
      - "Horvath/PT/Code/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "Horvath/PT/Code/package-lock.json"

      - name: Install dependencies
        run: |
          npm install
          npm install @wdio/cli @wdio/local-runner @wdio/mocha-framework @wdio/spec-reporter
        working-directory: Horvath/PT/Code

      - name: Install Chrome
        if: matrix.browser == 'chrome'
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Firefox
        if: matrix.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Edge
        if: matrix.browser == 'edge'
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Run WebdriverIO tests
        run: npx wdio run wdio.conf.js
        working-directory: Horvath/PT/Code
        env:
          BROWSER: ${{ matrix.browser }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            Horvath/PT/Code/test-results/
            Horvath/PT/Code/logs/
